# Generated by Django 4.1 on 2024-04-11 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_description_rule_rules_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule',
            name='id',
        ),
        migrations.AddField(
            model_name='rule',
            name='basemodel_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.basemodel'),
            preserve_default=False,
        ),
    ]
